plugin/Assets/PlayServicesResolver/Editor/PlayServicesResolver.cs

Existing code:
`Type type = Type.GetType(CurrentResolverName, true);`
Can produce an error in the editor "TypeLoadException: Could not load type ResolverVer1_1."
Adjusting the code to use the AssemblyName "GooglePlayServices" fixes the issue.

Fixes unity script compile error 'TypeLoadException'

---

source/JarResolverLib/src/Google.JarResolver/PlayServicesSupport.cs

EditorPrefs return empty string for missing keys, so the check in the
property misses this case. This causes build problems on CI environments
where there's no user setting for SDK path.

Fix SDK path in PlayServicesSupport

---

source/PlayServicesResolver/src/DefaultResolver.cs

Editor settings doesn't return null if the JDK path is not set, but an empty string.

Check if Editor JdkPath setting is null or empty

---

source/JarResolverLib/src/Google.JarResolver/PlayServicesSupport.cs

Fix for https://github.com/googlesamples/unity-jar-resolver/issues/48

Fixing https://github.com/googlesamples/unity-jar-resolver/issues/48

---

sample/Assets/PlayServicesResolver/Editor/Resolver.cs

Compile time check results in unreachable code warning on platforms other than Android

get rid of warning when not on Android using runtime check

---

CHANGELOG.md

Some dates in changelog are incorrect.
Fixed this according to commit information. 
Note: the exact day are left as is, but year and month are corrected.

Fixed incorrect dates in changelog.

---

source/PlayServicesResolver/src/JavaUtilities.cs

The ToolNotFoundException contains the right reference but the Unity Editor log contained the unresolved path, an empty string.

Properly reference java tool name in log

---

source/PlayServicesResolver/src/GradleTemplateResolver.cs
source/PlayServicesResolver/src/LocalMavenRepository.cs
source/PlayServicesResolver/src/PlayServicesResolver.cs
source/VersionHandlerImpl/src/FileUtils.cs
source/VersionHandlerImpl/src/ProjectSettings.cs

This is a fixed version of #258 
Includes;
Static checkout function.
Checkout code for dependency file, project settings, mainTemplate.gradle and POM writing.
In the previous request you raised concerns about;
https://github.com/googlesamples/unity-jar-resolver/blob/56d476e23464f797d8c90b5fac0958af2e0887db/source/PlayServicesResolver/src/PlayServicesResolver.cs#L1394
and 
https://github.com/googlesamples/unity-jar-resolver/blob/56d476e23464f797d8c90b5fac0958af2e0887db/source/PlayServicesResolver/src/GradleResolver.cs#L1070
However, I have found that deleting and adding files to be fine (standard resolution works with .aar files) and so i'm loathed to add any checkout code here. The problem seems to be modifying existing files that could be write protected.
Hopefully this request is more …

Version control checkout code for various files.

---

README.md
source/IOSResolver/src/IOSResolver.cs

https://github.com/googlesamples/unity-jar-resolver/issues/286
multiplied execution order attributes by 10 so podfile can be alterer after generation but before pod install runs

Allow appending to generated podfile before install runs

---

source/PlayServicesResolver/src/JavaUtilities.cs

add some lines to handle a new Unity OpenJDK path.
before
/Applications/Unity/Hub/Editor/{UnityVersion}/PlaybackEngines/AndroidPlayer/Tools/OpenJDK/{platform}
after
/Applications/Unity/Hub/Editor/{UnityVersion}/PlaybackEngines/AndroidPlayer/OpenJDK/

Unity OpenJDK path changed (2019.3.0, 2019.3.1)

---

sample/Assets/ExternalDependencyManager/Editor/SampleDependencies.xml
source/IOSResolver/src/IOSResolver.cs

Add ability to set XCode target from Dependencies file

---

source/AndroidResolver/src/AndroidAbis.cs
source/AndroidResolver/src/AndroidSdkManager.cs
source/AndroidResolver/src/CommandLine.cs
source/AndroidResolver/src/EmbeddedResource.cs
source/AndroidResolver/src/GradleResolver.cs
source/AndroidResolver/src/GradleWrapper.cs
source/AndroidResolver/src/JavaUtilities.cs
source/AndroidResolver/src/LocalMavenRepository.cs
source/AndroidResolver/src/PlayServicesResolver.cs
source/AndroidResolver/src/UnityCompat.cs
source/AndroidResolver/test/src/AndroidResolverIntegrationTests.cs
source/IOSResolver/src/IOSResolver.cs
source/IntegrationTester/src/Runner.cs
source/PackageManagerResolver/src/PackageManagerClient.cs
source/PackageManagerResolver/src/PackageManagerRegistry.cs
source/PackageManagerResolver/src/PackageManagerResolver.cs
source/PackageManagerResolver/src/PackageManifestModifier.cs
source/PackageManagerResolver/src/PackageMigrator.cs
source/PackageManagerResolver/test/PackageManagerClientIntegrationTests/PackageManagerClientIntegrationTests.cs
source/VersionHandler/src/VersionHandler.cs
source/VersionHandlerImpl/src/DialogWindow.cs
source/VersionHandlerImpl/src/EditorMeasurement.cs
source/VersionHandlerImpl/src/FileUtils.cs
source/VersionHandlerImpl/src/MiniJSON.cs
source/VersionHandlerImpl/src/RunOnMainThread.cs
source/VersionHandlerImpl/src/VersionHandlerImpl.cs
source/VersionHandlerImpl/unit_tests/src/EditorMeasurementTest.cs

Inline code documentation in C# files needs some love.
This PR improves:
- Ensure xml tags are always correctly closed
- Replace `return` tags with `returns` tags
- Fix outdated argument names in inline documentation
- Remove docs for removed arguments
- Add docs for some undocumented arguments
- Fix inline documentation to always starts with exactly three slashes `///`
- Fix regular comments to always starts with `//` and never with `///`
- Replace `<` in xmldoc with `&lt;`
- Fix missing quotes around values of xml attributes
- Ensure `<para>` tag is inside another tag
- Fix documentation on some enumeration values
- Fix few typos

Improved inline xml documentation

---

source/AndroidResolver/src/UnityCompat.cs

This fixes #322 where the unity editor will lose its target sdk setting between unity restarts if you have >28 selected in 2019, since unity AndroidSdkVersions enum does not contain values above 28. 
I have no idea why the function for getting the enum value is so roundabout in the first place, perhaps someone could inform me of why we have to go through the enum type and the string name when we have the correct value from the beginning? Are we expecting the enum int values to diverge from the string values at some point? 
I made minimal impact on the function since I don't understand the purpose of it :)

Fixes #322, Use the raw property value when the enum does not contain this value

---

source/VersionHandlerImpl/src/VersionHandlerImpl.cs

Added this check to avoid un-needed asset database searches on UpdateAssetsWithBuildTargets(EditorUserBuildSettings.activeBuildTarget); This commit solve perfomance issues when working on big projects.

Disabling update if the module is disabled in the Unity editor;

---

source/JarResolverLib/src/Google.JarResolver/Dependency.cs

Fix for issue #442. 
Dependnecy.cs was using `version1` string to detect a '+' suffix for the `version2` string in the `IsGreater` method.

Fix Dependency.cs IsGreater() detection of + characters on version2 string

---

source/AndroidResolver/src/UnityCompat.cs

Fixed the call to GetMethod for GetApplicationIdentifier so that the method lookup is no longer ambiguous in Unity 2021.2

Fix for #447

---

export_unity_package_config.json

Update `.meta` for editor libraries used in `.tgz` so that Unity 2021.2+ can properly load them.
This change the `export.json` config so that the export tool can properly override `.meta` file during package time.
The export tool will 
1. Use the `.meta` template here. https://github.com/googlesamples/unity-jar-resolver/blob/master/plugin/Assets/ExternalDependencyManager/Editor/Google.IOSResolver.dll.meta
2. Override the `.meta` while packaging `.tgz` based on the `override_metadata_upm` field. 
The `.meta` for `.unitypackage` will remain unchanged.

Properly enable EDM4U for Unity 2021.2. Fixed #477

---

source/AndroidResolver/src/CommandLine.cs
source/IOSResolver/src/IOSResolver.cs
source/IOSResolver/src/IOSResolverSettingsDialog.cs

Change default value of PodToolExecutionViaShellEnabled from true to false.
When shell execution is disabled, environment variables can be set explicitly for the cocoapods process instead of relying on the user's bash profile. This guarantees that LANG is set to a value that includes utf8, which is necessary when using CocoaPods version 1.11 or higher.
This resolves https://github.com/firebase/quickstart-unity/issues/1149

Change default value of PodToolExecutionViaShellEnabled to be compatible with CocoaPods 11.

---

source/VersionHandlerImpl/src/ProjectSettings.cs

See https://github.com/googlesamples/unity-jar-resolver/issues/425
This fixes the problem for git fighting with the BoM.
From the [Microsoft documentation](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlwriter.create?view=net-6.0):
> Remarks
> 
> XmlWriter always writes a Byte Order Mark (BOM) to the underlying data stream; however, some streams must not have a BOM. To omit the BOM, create a new XmlWriterSettings object and set the Encoding property to be a new UTF8Encoding object with the Boolean value in the constructor set to false.

Fixes #425 - Disable addition of BoM for the GvhProjectSettings

---

source/AndroidResolver/src/PlayServicesResolver.cs

The bug happens only if:
- "Patch mainTemplate.gradle" setting is enabled;
- You are resolving dependencies on Windows platform;
Examples of bad repo path string in mainTemplate.gradle:
file:///C:/Work/UnityProject\Assets/GeneratedLocalRepo/Firebase/m2repository
This happened because Path.Combine uses "\" as path separator for
windows platforms. But gradle actually expects not a regular path
but file URI, where "/" must be used as path separator.

Fixing maven repo path separator char

---

source/IOSResolver/src/IOSResolver.cs

CocoaPods has [introduced their CDN in 2019](https://blog.cocoapods.org/CocoaPods-1.8.0-beta/) and made it the default source. EDM's iOS resolver explicitly specifies the old source which has become extremely slow. The old source takes 10-15 minutes to clone on our build agents, making iOS builds needlessly slow. Using the CDN allows us to skip this step and start resolving dependencies right away.
This isn't obvious in local development because it only happens once and gets cached in `~/.cocoapods`, but disposable build agents have to run it with every single build. Caching the repo is slow because it's around a gigabyte and contains over one million files.
Resolves #470.

Speed up iOS resolver by 10-15 minutes

---

source/IOSResolver/src/IOSResolver.cs

As part of enabled swift, we had forced ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to YES, but that should not be necessary, as we also add an empty swift file to the target, which will enable swift. On top of that, the always embed flag seems to cause problems for some when submitting apps because of the additional framework folder it might make.
See:
https://github.com/firebase/firebase-unity-sdk/issues/349
and
https://github.com/googleads/googleads-mobile-unity/issues/2065

Remove the Always embed swift libraries flag

---

source/ExportUnityPackage/export_unity_package.py
source/ExportUnityPackage/export_unity_package_test.py

Update `export_unity_package.py` with the ability to handle `tvOS` build targets.

add tvOS structures to export_unity_package.py

---

source/VersionHandlerImpl/src/FileUtils.cs
source/VersionHandlerImpl/unit_tests/src/FileUtilsTest.cs

With certain version of Unity, ex. 2022.2.0b8 or 2023.1.0a11, `AssetDatabase.CreateFolder()` can fail when the folder name is version number like `9.0.0`. In this case, the API does not return empty guid but a guid with zeroes.
This change make sure that the folder can still be created using `Directory.CreateDirectory()`, which may not trigger AssetDatabase refresh in the older version of Unity.

Workaroud when `AssetDatabase.CreateFolder` failed

---

source/AndroidResolver/src/PlayServicesResolver.cs
source/VersionHandlerImpl/src/FileUtils.cs

Follow up for #543. When Unity failed to create folder using Unity API `AssetDatabase.CreateFolder()`, even with the workaround in #543, Unity would still generate two error message and there is no way to turn it off.
This change add an additional log after Unity API fails to inform the user to ignore this error.

Add log when Unity failed to create folder

---

source/IOSResolver/src/IOSResolver.cs

Expands the iOS resolver to also execute on tvOS BuildTargets.
This is part of a larger initiative to implement tvOS Support for the Firebase Unity SDK:
- [Unity Jar Resolver PR: add tvOS structures to export_unity_package.py](https://github.com/googlesamples/unity-jar-resolver/pull/540)
- [Unity SDK: tvOS build capability added to build_zips](https://github.com/firebase/firebase-unity-sdk/pull/465)
- [Unity SDK: tvOS metadata files](https://github.com/firebase/firebase-unity-sdk/pull/476)

Extend iOS Resolver with tvOS support

---

source/VersionHandlerImpl/src/EditorMeasurement.cs
source/VersionHandlerImpl/unit_tests/src/EditorMeasurementTest.cs

#484 
`EditorMeasurement` used to use `http://` instead of `https://` to report editor usage. This is causing later version of Unity  to log warnings and errors. Even though this is harmless, the logs still looks concerning.
This change basically change `http` to `https`.
- Local integration test with Unity 2018-2021.
- Manual test using Firebase Analytics with Unity 2022-2023 because EDM4U current cannot be built by the build tools from Unity 2022-2023.

Change EditorMeasurement to use secure connection (Fixed #484)

---

source/AndroidResolver/src/PlayServicesResolver.cs
source/AndroidResolver/src/SettingsDialog.cs

Adding two settings in Android Resolver settings to determine whether EDM4U inject custom local Maven repo path as a relative path or full path.
Before these settings, EDM4U has internal logic to always use full path when exporting project and relative path when not. Provide the new options so that the developers can choose to make it consistent or use full path to avoid certain Unity bugs.
Added a new task (Bug# 274671088) to add integration test for this. Currently manually verified with Unity 2022.2 and all integration tests are passed (primarily due to lack of test for full path scenario)

Add two Android Resolver settings related to custom local Maven repo path

---

.gitignore
build.gradle

Make sure the downloaded python will not be removed by `./gradlew clean` so that it is reusable for the next build.

Reuse the downloaded python

---

source/AndroidResolver/src/GradleResolver.cs

Fixes googlesamples/unity-jar-resolver#584 googlesamples/unity-jar-resolver#287

Do not explode AARs even if gradle project is not enabled

---

source/AndroidResolver/src/SettingsDialog.cs

AndroidX and Jetifier was introduce in 2019. There are higher and higher chance to have mix use of legacy support library and AndroidX support libraries.
Currently EDM4U can only detect if Jetifier is needed when `Custom Main Gradle Template` is not enabled, that is, when EDM4U downloads Android libraries to `Assets/Plugins/Android` folders. It is harder to detect the need of Jetfifier if the dependency is specified in Gradle templates.
This change will set `Use Jetifier` settings to `true` by default.

Enable Jetifier by default

---

source/AndroidResolver/src/GradleResolver.cs

Reverts googlesamples/unity-jar-resolver#593
This is failing the following tests
```
Test ResolveForGradleBuildSystemAndExport: FAILED
Test ResolveAddedDependencies: FAILED
Test ResolveRemovedDependencies: FAILED
Test DeleteResolvedLibraries: FAILED
```
Also, this change is a bit problematic since it means Android Resolver will NEVER explore AAR when export project is enabled.

Revert "Do not explode AARs even if gradle project is not enabled"

---

source/AndroidResolver/src/GradleResolver.cs
source/AndroidResolver/src/SettingsDialog.cs

Before this change, `Explode Aar` option in Android Resolver settings only applies when `Export Project` build setting is enabled, while Android Resolver always explode Aar libraries when the build setting is disabled.
This changes `Explode Aar` option to be applied no matter `Export Project` build setting is enabled or not. It is still recommended to enable this option for older version of Unity (5 to 2018) since certain version of Unity may generate broken Gradle project.
Fixes #584
Fixes #287

`Explode Aar` option applies to all cases

---

build.gradle
source/AndroidResolver/test/AndroidResolverIntegrationTestsUnityProject/ProjectSettings/GvhProjectSettings.xml
source/ExportUnityPackage/export_unity_package.py

Fix a couple of test fails for various reasons
- AndroidResolverIntegrationTest fails because auto-resolution is enabled from the beginning. This is messing around with the next test after the previous one is finished, specifically in interactive mode (not batch mode)
- Fix the use of deprecated Python package `distutils`
- Remove invalid PackageMigratorIntegration test because there is no registry to test against.

Fix failing tests

---

source/IOSResolver/src/IOSResolver.cs

On M1 macs, homebrew installs to /opt/homebrew/bin instead of /usr/local/bin. 
See https://github.com/Homebrew/brew/issues/9177 for an official source on this.
This change will increase the consistency of the pod command being found on such systems. This change was requested in #627

Add /opt/homebrew/bin to POD_SEARCH_PATHS

---

.github/workflows/build.yaml
.github/workflows/build_macos.yaml
gha/build_setup/action.yml

Enabled GHA to build EDM4U on macOS
- Build and upload both `.unitypackage` and `.tgz` as artifacts
- Show SHA256 hash for both packages.

GHA to build EDM4U on x86 Mac

---

.github/workflows/build.yaml

Input value from `workflow_dispatch` does not work if the action is triggered by cron job or other events.
Therefore, this change set default values, ex. unity_version, when the event type is not `workflow_dispatch`.

Fix Build GHA cron job

---

source/ExportUnityPackage/export_unity_package.py
source/ExportUnityPackage/export_unity_package_test.py

Sets the CPU value in the importer metadata for Android plugins when the exports.json specifies a CPU value for the Android plugin.
Fixes #638

Preserve Android plugin CPU value in exports.json for ExportUnityPackage

---

source/ExportUnityPackage/export_unity_package.py

If `tar` is run from a macOS, by default, it will create Mac Metadata file for every file and folder which starts with ".". This change makes sure that the archives does not include Mac Metadata file.

Prevent package from including Mac Metadata file

---

README.md
build.gradle

Enable test filtering through Gradle properties. See README.md for more information
In addition,    
- Update `reportAllTestsResult` task to include test type and test
module information.
- Update `README.md` to include information about test-related
properties.

Filter tests through Gradle properties

---

.github/workflows/test.yaml
build.gradle
gha/build_setup/action.yml

Add GHA for tests
Currently only run tests except for NUnit tests since it is broken from Unity 2019

GHA integration test

---

source/PackageManagerResolver/test/PackageManagerClientIntegrationTests/PackageManagerClientIntegrationTests.cs

`com.unity.entities` is no longer searchable from Unity 2020.

Fix PackageManagerClientIntegrationTests

---

.github/workflows/build.yaml
.github/workflows/test.yaml

- Prevent unintended labels from triggering test workflow. Only `tests-requested` label would trigger test workflow now.
- Prevent pull request from triggering build workflows since test
workflow would build EDM4U.
- Prevent test workflow from emitting error message just because
`grep` command did not get any failed tests.
- Add info for failed NUnit tests

Update Test and Build workflow

---

source/AndroidResolver/src/PlayServicesResolver.cs
source/AndroidResolver/src/SettingsDialog.cs
source/AndroidResolver/test/src/AndroidResolverIntegrationTests.cs

More dependencies, specifically Kotlin ones, will fail with the old resolution method.  We have encouraged users to use mainTemplate.gradle for several years now, so add logic such that for new projects will automatically enable it, and for projects that have already run the resolver before, a prompt window will appear asking them to do so first.  This prompt window checks against a new setting option, if users want to disable it.

Add logic to automatically enable gradle templates in new projects

---

build.gradle
source/IOSResolver/src/IOSResolver.cs
source/PackageManagerResolver/src/PackageManagerResolver.cs
source/VersionHandlerImpl/src/VersionHandlerImpl.cs

This resolves #524 by avoiding to needlessly save `GvhProjectSettings.xml` on every domain reload.
In all 3 modified files, the line
```
VerboseLoggingEnabled = VerboseLoggingEnabled;
```
does 3 things on domain reload because of `[InitializeOnLoad]`:
1. Loads `GvhProjectSettings.xml` if not already done
2. Writes `GvhProjectSettings.xml` unconditionally
3. Sets `logger.Level`
This PR removes step 2) which is unneeded and the cause of #524.
It's potentially possible that writing `GvhProjectSettings.xml` as a result of user interaction might still in some cases have a race condition. I didn't investigate this. However it's much less problematic than intermittent problems on domain reload.
The current code is correctly protecting critical sections, including saving `GvhProjectSettings.xml`, …

Fix project settings resetting on domain reload

---

source/VersionHandler/src/VersionHandler.cs
source/VersionHandlerImpl/src/VersionHandlerImpl.cs

To ensure AssetDatabase.FindAssets works no matter what the return type is, the variables have been changed to type var instead of string.
Note: This is replicating the changes from https://github.com/googlesamples/unity-jar-resolver/pull/684, since they are having issues with the CLA.

Update AssetDatabase.FindAssets usages return type

---

CHANGELOG.md
source/AndroidResolver/src/GradleTemplateResolver.cs
source/VersionHandlerImpl/src/FileUtils.cs

Unity 6 no longer includes that `@version` part for the Packages in `Library/PackageCache/packageid@version`, so handle both cases.
When installing a UPM package from a local directory, https://docs.unity3d.com/Manual/upm-ui-local.html, it was failing to relocate any srcaar files to the generated folder as aars because the path was not as expected, so change it to search for the m2repository part of the path and do it based on that.
Fixes #697 and #701

Fix issues with copying Android files from Packages

---

CHANGELOG.md
source/AndroidResolver/src/PlayServicesResolver.cs

Fixes #715.
Due to incompatibility of the `packagingOptions` keyword in Unity 6, this will create unecessary `mainTemplate.gradle.backup`. Android keyword [Packaging](https://developer.android.com/reference/tools/gradle-api/8.0/com/android/build/api/dsl/Packaging) is introduced in Android Gradle Plugin version 8.0+.
Use `packaging` keyword if AGP version is 8.0+, else use `packagingOptions`
Unity version | Gradle version | Android Gradle Plug-in version
-- | -- | --
Unity-6 | 8.4 | 8.3.0
2022.3 | 7.5.1 | 7.4.2
2021.3 | 7.5.1 | 7.4.2
e.g.
```
// Android Resolver Exclusions Start
android {
packaging {
exclude ('/lib/arm64-v8a/*' + '*')
exclude ('/lib/armeabi/*' + '*')
exclude ('/lib/mips/*' + '*')
exclude ('/lib/mips64/*' + '*')
exclude ('/lib/x86/*' + '*')
exclude ('/lib/x86_64/*' + '*')
} …
```

Replace `packagingOptions` to `packaging` if AGP is 8.0+

---

CHANGELOG.md
source/AndroidResolver/src/PlayServicesResolver.cs

Incorrect conditional checker used on #718. Should use greater than or equal sign comparison.

Reverse conditional checker

---

plugin/Assets/ExternalDependencyManager/Editor/Google.IOSResolver.dll.meta
source/ExportUnityPackage/export_unity_package.py
source/IOSResolver/src/IOSResolver.cs

By default, DLLs imported into Unity will validate all their references at load time. The iOS Resolver depends on the Unity iOS Support Library being present, which is not true by default for Windows developers. By turning off validateReferences, the library will no longer throw an exception at load time, but instead at runtime, which the library itself can handle instead.
https://github.com/googlesamples/unity-jar-resolver/issues/412
https://github.com/googlesamples/unity-jar-resolver/issues/622

Turn off validateReferences for the iOS Resolver
